### ISSUE TITLE
macos 13 build

### ISSUE THREAD

**Issue by PiotrJustyna** [dQuadrant/cardano-marketplace#4]
Am I the only one having problems building a local environment for this? Pulled the code, opened in vscode, reopened in container and the environment failed building with the following error:

```bash
[2023-06-20T15:09:53.216Z] 
8c70b848eded: Extracting    432MB/432MB
[2023-06-20T15:09:53.226Z] docker: failed to register layer: write /root/.cabal/packages/hackage.haskell.org/01-index.tar: no space left on device.
See 'docker run --help'.
[2023-06-20T15:09:53.236Z] Stop (485669 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/JustPi01/Documents/code/cardano-marketplace,target=/workspaces/cardano-marketplace,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace -l devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"customizations":{"vscode":{"extensions":["haskell.haskell"],"settings":{"haskell.manageHLS":"GHCup"}}}}] dquadrant/cardano-devcontainer:1.35.0 -c echo Container started
[2023-06-20T15:09:53.246Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace --filter label=devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json
[2023-06-20T15:09:53.501Z] Stop (255 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace --filter label=devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json
[2023-06-20T15:09:53.501Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/JustPi01/Documents/code/cardano-marketplace,target=/workspaces/cardano-marketplace,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace -l devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"customizations":{"vscode":{"extensions":["haskell.haskell"],"settings":{"haskell.manageHLS":"GHCup"}}}}] dquadrant/cardano-devcontainer:1.35.0 -c echo Container started
[2023-06-20T15:09:53.501Z] trap "exit 0" 15
[2023-06-20T15:09:53.501Z] exec "$@"
[2023-06-20T15:09:53.502Z] while sleep 1 & wait $!; do :; done -
[2023-06-20T15:09:53.502Z]     at mte (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3286)
[2023-06-20T15:09:53.502Z]     at IN (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3222)
[2023-06-20T15:09:53.502Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-06-20T15:09:53.502Z]     at async Ote (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:3660)
[2023-06-20T15:09:53.502Z]     at async Hf (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:4775)
[2023-06-20T15:09:53.502Z]     at async Qre (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10371)
[2023-06-20T15:09:53.502Z]     at async Zre (/Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10112)
[2023-06-20T15:09:53.504Z] Stop (488870 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/JustPi01/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-cc06d1e2-bccb-4fec-a42f-ae79a3d2d3561687273303591 --workspace-folder /Users/JustPi01/Documents/code/cardano-marketplace --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace --id-label devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-20T15:09:53.504Z] Exit code 1
[2023-06-20T15:09:53.506Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/JustPi01/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/JustPi01/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-cc06d1e2-bccb-4fec-a42f-ae79a3d2d3561687273303591 --workspace-folder /Users/JustPi01/Documents/code/cardano-marketplace --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/JustPi01/Documents/code/cardano-marketplace --id-label devcontainer.config_file=/Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/JustPi01/Documents/code/cardano-marketplace/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-20T15:09:53.506Z] Exit code 1
```

I'm not sure what the problem is 🤔

**Comment by PiotrJustyna** [comment]
Oops, now I see it:

`01-index.tar: no space left on device`

Let me check this tomorrow.

**Comment by PiotrJustyna** [comment]
Yeah, plutus pioneer image took 15GB our of my very conservative default docker setup 😅 Updated my docker configuration, cleaned up dangling images and it's all working fine now. Sorry about the false alarm, closing the issue now.
